services:
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    # image: mini-app-cicd_jenkins:latest
    ports:
      - "${JENKINS_PORT}:8080"
      - "${JENKINS_AGENT_PORT}:${JENKINS_AGENT_PORT}"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # image: mini-app-cicd_backend:latest
    ports:
      - "${BACKEND_PORT}:3000"
    environment:
      - NODE_ENV=production
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # image: mini-app-cicd_frontend:latest
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production

volumes:
  jenkins-data: