pipeline {
    agent any
    stages {
        stage('Test Clone') {
            steps {
                git branch: 'main', url: 'https://github.com/haikali3/mini-app-cicd.git'
            }
        }
    }
}
